### PR TITLE
general structure of db, will need to tweak more

### PR DESCRIPTION
**Pull request by BrandonDenton**
I have laid out the general structure of the database, but I will need to tweak a couple elements and freshen up on Knex over the next day.

### CODE REVIEW

**Review by le3bl — CHANGES_REQUESTED** [review]
Couple of issues I am seeing here. The primary key column 'id' is not defined. Not entirely sure this needs to be defined with Laravel or not. I would assume articleID would be the auto-incrementing primary key which would need to be an int. We would also want a string to contain the URI of the article and this would need to be indexed for a faster lookup.
This spec does not support a sound model for voting as it does not track who has voted and when the vote was cast. This would allow for multiple votes from the same user and not allow for a "trending" type of analytic.
If we are going to use strings as keys then we will not be able to use incrementing which will result in poor performance in a database with many relationships.
This model also lacks a Permissions and Role-Permissions relational table which we are going to need to allow for the approval of ClickBait Answer Approvals.
Finally any table with multiple IDs would typically be considered a relation table and would perform best using indexed foreign keys instead of string values.

**Comment by le3bl** [comment]
Here is more or less what I was envisioning:

articles
	id - int - incrementing - unsigned - primary key (indexed)
	uri - string - indexed (for search capabilities)
	createdDate - datetime
	modifiedDate - datetime
	userId - int - unsigned - foreign key -> Users.Id - indexed
	isDeleted - bool

users
	id - int - incrementing - unsigned - primary key (indexed)
	uri - string
	authType - string/int (not sure how we will be doing SSO)
	isActive - bool
	createdDate - datetime
	modifiedDate - datetime
	
userArticles
	id - int - incrementing - unsigned - primary key (indexed)
	articleId - int - unsigned - foreign key -> Articles.Id - indexed
	userId - int - unsigned - foreign key -> Users.Id - indexed
	
roles
	id - int - incrementing - unsigned - primary key (indexed)
	name/uri - string
	createdDate - datetime
	modifiedDate - datetime
	isDefault - bool

userRoles
	id - int - incrementing - unsigned - primary key (indexed)
	userId - int - unsigned - foreign key -> Users.Id - indexed
	roleId - int - unsigned - foreign key -> Roles.Id - indexed
	isActive - bool
	createdDate - datetime
	modifiedDate - datetime
	
permissions
	id - int - incrementing - unsigned - primary key (indexed)
	name/uri - string
	createdDate - datetime
	modifiedDate - datetime
	
rolePermissions
	id - int - incrementing - unsigned - primary key (indexed)
	roleId - int - unsigned - foreign key -> Roles.Id - indexed)
	permissionId - int - unsigned - foreign key -> Permissions.Id  -indexed
	
userArticleVotes
	id - int - incrementing - unsigned - primary key (indexed)
	userId - int - unsigned - foreign key -> Users.Id - indexed
	articleId - int - unsigned - foreign key -> Article.Id - indexed
	isUpVote - bool (I think this is how reddit does it)
	createdDate - datetime
	modifiedDate - datetime
	
tags
	id - int incrementing - unsigned - primary key (indexed)
	title - string - indexed (for search capabilities)
	createdDate
	userId - int - unsigned - foreign key -> Users.Id - indexed
	
articleTags
	id - int - incrementing - unsigned - primary key (indexed)
	tagId - int - unsigned - foreign key -> Tags.Id - indexed
	articleId - int - unsigned - foreign key -> Articles.Id - indexed
	userId - int - unsigned - foreign key -> Users.Id - indexed
	createdDate - datetime

**Comment by KixPanganiban** [comment]
This looks good @BrandonDenton, unfortunately we've moved to Laravel. See #10. You can re-do the models in Laravel, and we can merge that upstream instead.

**Comment by BrandonDenton** [comment]
Understood @KixPanganiban. I'm seeing a lot more documentation on Laravel's SQL functions anyway. I'm converting what I have and will submit a pull request in a few minutes.

**Comment by BrandonDenton** [comment]
new pull request made with more appropriate script, closing this one

**Pull request closed without merging**
