### PR TITLE
added Vagrant configs

### PR DESCRIPTION
**Pull request by chriscasto**
The Vagrant configuration has been set up to install and configure all packages, services, and dependencies necessary to get the server running.

### CODE REVIEW

**Comment by cgrs** [comment]
Do you have a setup guide? Or have you followed any manual?

**Comment by chriscasto** [comment]
I put a small README in the vagrant directory with some brief instructions, but the Vagrant documentation should serve as the authoritative source for anything specific to Vagrant itself.  For anyone unfamiliar with Vagrant, the basic flow is install Vagrant, go to project directory on command line, and run `vagrant up`.  It will automatically build and configure the environment to make it ready for development. The current configuration automatically installs PHP 7.1, nginx, composer, and all of the app's dependencies and makes sure all services are running.

**Comment by cgrs** [comment]
Oh sorry, didn't see the README 😅. I'm familiar with Vagrant, but I lack some practice on automation tools, that's why I asked you.Anyway, have you checked out [Homestead](https://laravel.com/docs/master/homestead)?El 24 abr. 2017 20:15, chriscasto <notifications@github.com> escribió:




I put a small README in the vagrant directory with some brief instructions, but the Vagrant documentation should serve as the authoritative source for anything specific to Vagrant itself. For anyone unfamiliar with Vagrant, the basic flow is install Vagrant,
 go to project directory on command line, and run vagrant up. It will automatically build and configure the environment to make it ready for development. The current configuration automatically installs PHP 7.1, nginx, composer, and all of the
 app's dependencies and makes sure all services are running.
—
You are receiving this because you commented.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.









El 24 abr. 2017 20:15, chriscasto <notifications@github.com> escribió:




I put a small README in the vagrant directory with some brief instructions, but the Vagrant documentation should serve as the authoritative source for anything specific to Vagrant itself. For anyone unfamiliar with Vagrant, the basic flow is install Vagrant,
 go to project directory on command line, and run vagrant up. It will automatically build and configure the environment to make it ready for development. The current configuration automatically installs PHP 7.1, nginx, composer, and all of the
 app's dependencies and makes sure all services are running.
—
You are receiving this because you commented.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.

**Comment by cgrs** [comment]
Oh sorry, didn't see the README 😅. I'm familiar with Vagrant, but I lack some practice on automation tools, that's why I asked you.
Anyway, have you checked out [Homestead](https://laravel.com/docs/master/homestead)?

**Comment by chriscasto** [comment]
Homestead is for a different use case. It's nice when you're just contributing to a generic project and you don't care where the data goes or how the servers are configured because there won't be a single right answer. In our case, however,  the app will be hosted in a single place with a known configuration, and the power of Vagrant+Puppet means we don't have to do the same work more than once. By using the same basic configuration in both places, the developers will be working in an environment that's as close to the production environment as possible.

**Comment by cgrs** [comment]
Thanks for the explanation! I expect this pull to be merged ASAP, since it will save a lot of time. Thanks again for making the effort to clarify my doubts :wink:

**Review by KixPanganiban — APPROVED** [review]

**Pull request merged**
